name: Build
on: push

jobs:
    build:
        runs-on: 'ubuntu-latest'
        steps:
            - name: test
              run: |
                SCAN_IMAGE='
                    ARG image

                    FROM ${image} as image

                    FROM busybox AS scanner

                    RUN --mount=type=bind,target=/scanner,from=docker/scout-sbom-indexer:1-doi \
                        --mount=type=bind,target=/image,from=image \
                        set -ex; \
                        mkdir /out; \
                        export DOCKER_SCOUT_ENVIRONMENT=indexer; \
                        export DOCKER_SCOUT_SBOM_CATALOGERS=php-composer-lock,erlang-otp-application,lua-rock-cataloger; \
                        export BUILDKIT_SCAN_DESTINATION=/out; \
                        export BUILDKIT_SCAN_SOURCE=/image; \
                        /scanner/sbom-indexer

                    FROM scratch

                    COPY --from=scanner /out /
                '
                image=node:22-bookworm-slim && arch=linux/amd64 && output=$(mktemp -d) \
                && echo $SCAN_IMAGE | docker buildx b . --platform $arch -f - --build-arg image=$image -o $output \
                && jq $output/image.spdx.json | column -ts $'\t' \
                && rm -rf $output
