name: Build
on: push

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
                image: ['docker/scout-sbom-indexer:1.14.0', 'docker/scout-sbom-indexer:8ccd22f']
        runs-on: ${{ matrix.os }}
        steps:
          - name: Setup
            run: |
              docker buildx create \
                --name "container-builder" \
                --node "container-builder" \
                --platform "linux/amd64" \
                --driver docker-container \
                --bootstrap --use
          - name: test
            env:
              IMAGE: ${{ matrix.image }}
            run: echo 'FROM traefik' | docker buildx b . --sbom="generator=$IMAGE" -f -
